# NEVER EDIT MANUALLY. Changes here will be overwritten by Copier
_commit: '2811148'
_src_path: https://github.com/easyscience/templates-copier.git
app_docs_url: https://docs.easydiffraction.org/lib
app_repo: diffraction-app
description: efewfw
has_app: true
has_lib: true
hub_repo: diffraction
hub_url: https://easydiffraction.org
lib_docs_url: https://docs.easydiffraction.org/lib
lib_repo: diffraction-lib
package_name: easydiffraction
project_name: EasyDiffraction
template_dir: desktop-app
year: 2025
