# NEVER EDIT MANUALLY. Changes here will be overwritten by Copier
_commit: dc9d13f
_src_path: gh:easyscience/templates-copier
description: ejnfejkwnvkj
docs_url: wefgew
package_name: superduper
project_name: SuperDuper
repo: superduper-lib
site_url: gerwg
template_type: project-lib
year: 2024
