# NEVER EDIT MANUALLY. Changes here will be overwritten by Copier
_commit: 6768ccf
_src_path: gh:easyscience/templates-copier
app_docs_url: https://docs.easydiffraction.org/lib
app_repo: diffraction-app
description: efewfw
has_app: true
has_lib: true
hub_repo: diffraction
hub_url: https://easydiffraction.org
lib_docs_url: https://docs.easydiffraction.org/lib
lib_repo: diffraction-lib
package_name: easydiffraction
project_name: EasyDiffraction
template_dir: python-lib
year: 2025
