# NEVER EDIT MANUALLY. Changes here will be overwritten by Copier
_commit: 09b811b
_src_path: https://github.com/easyscience/templates-python-lib.git
lib_max_python: '3.12'
lib_min_python: '3.9'
lib_package_name: easydiffraction
project_description: Diffraction data analysis
project_name: EasyDiffraction
project_year: 2025
repos_lib: diffraction-lib
